---
title: "EGKK"
author: "Performance Review Unit"
date: "02/06/2020"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

download with EGKK ARP; taken from OSN: https://opensky-network.org/airport-profile?icao=EGKK
apt <- data.frame(ICAO = "EGKK", LON = -0.19027799, LAT = 51.148101807, ELEV = 202)


```{r}
pth <- "./data-raw/"
fns <- list.files(path = pth, pattern = "^osn_EGKK_")

osn_col_spec <- cols(
  time = col_double(),
  icao24 = col_character(),
  lat = col_double(),
  lon = col_double(),
  velocity = col_double(),
  heading = col_double(),
  vertrate = col_double(),
  callsign = col_character(),
  onground = col_logical(),
  alert = col_logical(),
  spi = col_logical(),
  squawk = col_double(),
  baroaltitude = col_double(),
  geoaltitude = col_double(),
  lastposupdate = col_double(),
  lastcontact = col_double(),
  hour = col_double()
)

ds  <- paste0(pth, fns) %>%
  purrr::map_dfr(.f=~read_csv(., col_types = osn_col_spec))

ds <- ds %>% mutate(time = lubridate::as_datetime(time))
```